DirectorsManual.Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirectorsManual.Domain.Entities;
using DirectorsManual.Domain.Abstract;
using DirectorsManual.Web.Models;

namespace DirectorsManual.Web.Controllers
{
    public class CartController : Controller
	{
		public PartialViewResult Summary(Cart cart)
		{
			return PartialView(cart);
		}


		private IProductRepository repository;
		private IOrderProcessor orderProcessor;
		private object p;

		public CartController(IProductRepository repo, IOrderProcessor processor)
		{
			repository = repo;
			orderProcessor = processor;
		}

		public CartController(object p)
		{
			this.p = p;
		}

		public RedirectToRouteResult AddToCart(Cart cart, int ID, string returnUrl)//имена параметров соответствуют элементам <input> в HTML-формах, 
																		//созданных в представлении ProductSummary.cshtml.
		{
			TProduct game = repository.Products
				.FirstOrDefault(g => g.ID == ID);

			if (game != null)
			{
				cart.AddItem(game, 1);
			}
			return RedirectToAction("Index", new { returnUrl });//браузеру отправляется инструкция перенаправления HTTP, заставляя браузер запросить новый URL
																//браузер запросит URL, который вызывает метод действия Index() контроллера Cart.
		}

		public RedirectToRouteResult RemoveFromCart(Cart cart, int ID, string returnUrl)
		{
			TProduct game = repository.Products
				.FirstOrDefault(g => g.ID == ID);

			if (game != null)
			{
				cart.RemoveLine(game);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		//public Cart GetCart()
		//{//исп. для создания корзины в виде отдельного сеанса для каждого пользователя

		//	Cart cart = (Cart)Session["Cart"];//извлечение объекта DataSet из памяти сеанса
		//	if (cart == null)
		//	{
		//		cart = new Cart();
		//		Session["Cart"] = cart;//добавить объект в состояние сеанса
		//	}
		//	return cart;
		//}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel
			{
				Cart = cart,
				ReturnUrl = returnUrl
			});
		}


		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}


		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			if (cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("", "Извините, ваша корзина пуста!");
			}

			if (ModelState.IsValid)
			{
				orderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}

		//public ViewResult Index(string returnUrl)//визуализирует корзину
		//{
		//	return View(new CartIndexViewModel
		//	{
		//		Cart = GetCart(),
		//		ReturnUrl = returnUrl
		//	});
		//}
	}
}

DirectorsManual.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirectorsManual.Domain.Abstract;
using DirectorsManual.Domain.Entities;
using DirectorsManual.Web.Models;

namespace DirectorsManual.Web.Controllers
{
    public class ProductController : Controller
    {
		private IProductRepository repository;
		public int pageSize = 4;
		public ProductController(IProductRepository repo)//конструктор, который объявляет зависимость от интерфейса IGameRepository
		{
			repository = repo;
			//приводит к внедрению библиотекой Ninject данной
			//зависимости для хранилища товаров при создании экземпляра класса контроллера
		}

		public ViewResult List(string category, int page = 1)
		{
			ProductsListViewModel model = new ProductsListViewModel
			{
				Products = repository.Products
					.Where(p => category == null || p.Category == category)
					.OrderBy(prod => prod.ID)
					.Skip((page - 1) * pageSize)
					.Take(pageSize),
				PagingInfo = new PagingInfo
				{
					CurrentPage = page,
					ItemsPerPage = pageSize,
					TotalItems = category == null ?
			repository.Products.Count() :
			repository.Products.Where(prod => prod.Category == category).Count()
				},
				CurrentCategory = category
			};
			return View(model);
		}

		public FileContentResult GetImage(int ID)
		{
			TProduct product = repository.Products
				.FirstOrDefault(g => g.ID == ID);

			if (product != null)
			{
				return File(product.ImageData, product.ImageMimeType);
			}
			else
			{
				return null;
			}
		}
       
        //public ViewResult List()
        //{
        //	//будет визуализировать представление, отображающее полный список товаров
        //	return View(repository.Products);
        //}
    }
}

DirectorsManual.Web/Views/Shared/ProductSummary.cshtml
@model DirectorsManual.Domain.Entities.TProduct

<div class="well">
	@if (Model.ImageData != null)
	{
		<div class="pull-left" style="margin-right: 10px">
			<img class="img-thumbnail" width="75" height="75"
				 src="@Url.Action("GetImage", "Product",
                new { Model.ID })" />
		</div>
	}
	<h3>
		<strong>@Model.Name_Product</strong>
		<span class="pull-right label label-primary">@Model.Price.ToString("# грн.")</span>
	</h3>
	@using (Html.BeginForm("AddToCart", "Cart"))
	{
		<div class="pull-right">
			@Html.HiddenFor(x => x.ID)
			@Html.Hidden("returnUrl", Request.Url.PathAndQuery)
			<input type="submit" class="btn btn-success" value="Добавить в корзину" />
		</div>
	}
	<span class="lead">@Model.Description</span>
</div>

DirectorsManual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title – приложение Director's Manual</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	<link href="~/Content/ErrorStyles.css" rel="stylesheet" />
	<link href="~/Content/adelina.css" rel="stylesheet" />
	<script src="~/Content/forLayoutA.js"></script>
</head>
<body>

    <!--/.Navbar -->
    @*<div class="navbar-brand" href="#">
            <img src="~/Images/default.jpg" width="60" height="30" alt="">
        </div>*@
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Кнопка «Гамбургер» -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                    <span class=sr-only>Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Бренд или название сайта -->
                @Html.ActionLink("Director's Manual", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                  
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("About us", "About", "Home")</li>
                            <li role="separator" class="divider"></li><!--Разделитель между элементами в списке -->
                            <li>@Html.ActionLink("Contacts", "Contact", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Catalog", "List", "Product")</li>

                    <li>@Html.Action("Summary", "Cart")</li>
                    @if (User.IsInRole("admin"))
                    {
                        <li>
                            @Html.ActionLink("ADMIN", "Index", new { area = "Admin", controller= "Admin" })
                            @*@Html.ActionLink("ADMIN", "Index", "Admin")*@
                        </li>
                    }
                </ul>
                @if (Request.IsAuthenticated)
                {
                    @Html.Partial("_LoginPartial")
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Registration", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                <li>@Html.ActionLink("Login", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                            </ul>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
    @RenderSection("Splacs", false)

    <div class="container body-content">
        @RenderBody()

        <footer>
            <p>&copy; @DateTime.Now.Year – приложение Director`s Manual</p>
        </footer>
    </div>
    <script src="/js/bootstrap-submenu.min.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $('[data-toggle="dropdown"]').submenupicker();
        });
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>